/**
 * Convention-based path to a responsive WebP variant, generated by
 * scripts/build-images.mjs: /images/projects/foo.png -> /images/projects/foo-640.webp
 */
export function webpVariant(src: string, width: number): string {
  const dot = src.lastIndexOf(".");
  const base = dot === -1 ? src : src.slice(0, dot);
  return `${base}-${width}.webp`;
}

export function webpSrcSet(src: string, widths: readonly number[]): string {
  return widths.map((w) => `${webpVariant(src, w)} ${w}w`).join(", ");
}
